### ISSUE TITLE
Unable to download the excel project sheet

### ISSUE THREAD

**Issue by Aditya-Menon-Analyst** [AlexTheAnalyst/Excel-Tutorial#5]
Hey guys! I am unable to download the excel project file, tried to open it in incognito and it didn't work. If any of have the file pls share it with me here. Thanks ; )

**Comment by Aditya-Menon-Analyst** [comment]
I am now able to download the file ; )

**Comment by Biveren** [comment]
How did you do it pls

**Comment by sheffycakes** [comment]
How can download the data set for conditioning and formatting??, I couldn't find it here
